spring.application.name=MiniERP
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_erp
spring.datasource.username=postgres
spring.datasource.password=sofia2808
spring.jpa.hibernate.ddl-auto=validate