server.port=${SERVER_PORT}

spring.application.name=MiniERP

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA solo valida que coincida con el esquema creado por Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public

flyway.enabled=true
flyway.locations=classpath:db/migration
flyway.baseline-on-migrate=true

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION}

# Facturas
app.invoice.output-dir=./facturas

# Swagger
springdoc.swagger-ui.path=/docs
