server.port=8080

spring.application.name=MiniERP

spring.datasource.url=jdbc:postgresql://localhost:5432/mini_erp
spring.datasource.username=postgres
spring.datasource.password=sofia2808
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA solo valida que coincida con el esquema creado por Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public

flyway.enabled=true
flyway.locations=classpath:db/migration
flyway.baseline-on-migrate=true

# JWT
app.jwt.secret=${JWT_SECRET:CAMBIAR_ESTE_SECRETO_EN_PRODUCCION_MINIMO_32_BYTES}
app.jwt.expiration-ms=28800000

# Facturas
app.invoice.output-dir=./facturas

# Swagger
springdoc.swagger-ui.path=/docs
